// <auto-generated />
namespace ToDo_CS.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class changetodo2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(changetodo2));
        
        string IMigrationMetadata.Id
        {
            get { return "201705291412186_changetodo2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
